### PR TITLE
Adding Kattana to the MultiversX Dev List

### PR DESCRIPTION
**Pull request by dmytrobieliaiev**
I hope this pull request finds you well. 
I am writing to propose the addition of Kattana, an advanced trading terminal, to the MultiversX Dev Resources. Kattana brings a wealth of features and benefits that can greatly enhance the trading efficiency and user experience for MultiversX users.

Seamless Integration: Kattana is designed to integrate smoothly with existing exchanges and trading platforms. The implementation of Kattana within MultiversX can be seamless and provide users with a unified trading experience across multiple exchanges and pairs, for example:

- [WEGLD/USDC](https://app.kattana.io/ELROND/erd1qqqqqqqqqqqqqpgqeel2kumf0r8ffyhth7pqdujjat9nx0862jpsg2pqaq)
- [ZPAY/USDC](https://app.kattana.io/ELROND/erd1qqqqqqqqqqqqqpgqtjhhs49h0q2ncld64l3thtk7s7yuw47v2jps8emt0v)

I kindly request you review this proposal and consider incorporating Kattana into MultiversX. I believe it will significantly benefit the trading community and further solidify MultiversX as a comprehensive and user-friendly trading platform.

### CODE REVIEW

**Comment by juliancwirko** [comment]
Hi, nice project! But I would like to see more MultiversX-related tools and services for developers here. 
But let's see what others will say.

**Comment by PABourdais** [comment]
Not sure it's the good place for it

**Comment by dmytrobieliaiev** [comment]
> Hi, nice project! But I would like to see more MultiversX-related tools and services for developers here. But let's see what others will say.

I've considered moving it to the API section, but I think the product itself is more understandable for end-users.
Developers can use free API to request data for different cases, for example:
- Get big trades on Multiversx chain: https://api-staging.kattana.trade/docs/index.html#/trades/get_big_trades__value___limit_ [example](https://api-staging.kattana.trade/big-trades/10000/10?network=ELROND)
- Get trades on pair https://api-staging.kattana.trade/docs/index.html#/trades/get_trades__network___address_ [example](https://api-staging.kattana.trade/trades/ELROND/erd1qqqqqqqqqqqqqpgqeel2kumf0r8ffyhth7pqdujjat9nx0862jpsg2pqaq)

And more other things like charts, token statistics, pair reserves, subscriptions to wallet events and etc.

**Review by PaulHendi — COMMENTED** [review]
The app is actually nice, but not directly related to MultiversX nor scan/API

**Pull request closed without merging**
